import { RyzenInfoFields, RyzenInputParams } from './ryzenadj'

export const RyzenInfoParamsMap: Partial<Record<RyzenInfoFields, RyzenInputParams>> = {
  STAPM_LIMIT: 'stapm-limit',
  PPT_LIMIT_FAST: 'fast-limit',
  PPT_LIMIT_SLOW: 'slow-limit',
  StapmTimeConst: 'stapm-time',
  SlowPPTTimeConst: 'slow-time',
  PPT_LIMIT_APU: 'apu-slow-limit',
  TDC_LIMIT_VDD: 'vrm-current',
  TDC_LIMIT_SOC: 'vrmsoc-current',
  EDC_LIMIT_VDD: 'vrmmax-current',
  EDC_LIMIT_SOC: 'vrmsocmax-current',
  THM_LIMIT_CORE: 'tctl-temp',
  STT_LIMIT_APU: 'apu-skin-temp',
  STT_LIMIT_dGPU: 'dgpu-skin-temp',
  POWER_SAVING: 'power-saving',
  MAX_PERFORMANCE: 'max-performance'
} as const

export const RyzenInfoFieldsMap: Partial<Record<RyzenInfoFields, RyzenInputParams>> = {
  STAPM_VALUE: 'stapm-limit',
  PPT_VALUE_FAST: 'fast-limit',
  PPT_VALUE_SLOW: 'slow-limit',
  StapmTimeConst: 'stapm-time',
  SlowPPTTimeConst: 'slow-time',
  PPT_VALUE_APU: 'apu-slow-limit',
  TDC_VALUE_VDD: 'vrm-current',
  TDC_VALUE_SOC: 'vrmsoc-current',
  EDC_VALUE_VDD: 'vrmmax-current',
  EDC_VALUE_SOC: 'vrmsocmax-current',
  THM_VALUE_CORE: 'tctl-temp',
  STT_VALUE_APU: 'apu-skin-temp',
  STT_VALUE_dGPU: 'dgpu-skin-temp',
  POWER_SAVING: 'power-saving',
  MAX_PERFORMANCE: 'max-performance'
} as const

export const RyzenParamsDescriptionMap: Record<RyzenInputParams, string> = {
  'stapm-limit': 'Sustained Power Limit (mW)',
  'fast-limit': 'Actual Power Limit (mW)',
  'slow-limit': 'Average Power Limit (mW)',
  'slow-time': 'Slow PPT Constant Time (s)',
  'stapm-time': 'STAPM constant time (s)',
  'tctl-temp': 'Tctl Temperature Limit (° C)',
  'vrm-current': 'VRM Current Limit (mA)',
  'vrmsoc-current': 'VRM SoC Current Limit (mA)',
  'vrmgfx-current': 'VRM GFX Current Limit (mA)',
  'vrmcvip-current': 'VRM CVIP Current Limit (mA)',
  'vrmmax-current': 'VRM Maximum Current Limit (mA)',
  'vrmsocmax-current': 'VRM SoC Maximum Current Limit (mA)',
  vrmgfxmax_current: 'VRM GFX Maximum Current Limit (mA)',
  'psi0-current': 'PSI0 VDD Current Limit (mA)',
  psi3cpu_current: 'PSI3 CPU Current Limit (mA)',
  'psi0soc-current': 'PSI0 SoC Current Limit (mA)',
  psi3gfx_current: 'PSI3 GFX Current Limit (mA)',
  'max-socclk-frequency': 'Maximum SoC Clock Frequency (MHz)',
  'min-socclk-frequency': 'Minimum SoC Clock Frequency (MHz)',
  'max-fclk-frequency': 'Maximum Transmission (CPU-GPU) Frequency (MHz)',
  'min-fclk-frequency': 'Minimum Transmission (CPU-GPU) Frequency (MHz)',
  'max-vcn': 'Maximum Video Core Next (VCE - Video Coding Engine) (MHz)',
  'min-vcn': 'Minimum Video Core Next (VCE - Video Coding Engine) (MHz)',
  'max-lclk': 'Maximum Data Launch Clock (MHz)',
  'min-lclk': 'Minimum Data Launch Clock (MHz)',
  'max-gfxclk': 'Maximum GFX Clock (MHz)',
  'min-gfxclk': 'Minimum GFX Clock (MHz)',
  'prochot-deassertion-ramp': 'Ramp Time After Prochot is Deasserted',
  'apu-skin-temp': 'APU Skin Temperature Limit (° C)',
  'dgpu-skin-temp': 'dGPU Skin Temperature Limit (° C)',
  'apu-slow-limit': 'APU PPT Slow Power limit for A+A dGPU platform (mW)',
  'skin-temp-limit': 'Skin Temperature Power Limit (mW)',
  'gfx-clk': 'Forced Clock Speed MHz (Renoir Only)',
  'oc-clk': 'Forced Core Clock Speed MHz (Renoir and up Only)',
  'oc-volt': 'Forced Core VID (Renoir and up Only)',
  'enable-oc': 'Enable OC (Renoir and up Only)',
  'disable-oc': 'Disable OC (Renoir and up Only)',
  'set-coall': 'All core Curve Optimiser',
  'set-coper': 'Per core Curve Optimiser',
  'set-cogfx': 'iGPU Curve Optimiser',
  'power-saving': 'Hidden options to improve power efficiency',
  'max-performance': 'Hidden options to improve max performance'
}

export const RyzenParamsUnitsMap: Partial<Record<RyzenInputParams, string>> = {
  'stapm-limit': 'mW',
  'fast-limit': 'mW',
  'slow-limit': 'mW',
  'slow-time': 's',
  'stapm-time': 's',
  'tctl-temp': '° C',
  'vrm-current': 'mA',
  'vrmsoc-current': 'mA',
  'vrmgfx-current': 'mA',
  'vrmcvip-current': 'mA',
  'vrmmax-current': 'mA',
  'vrmsocmax-current': 'mA',
  vrmgfxmax_current: 'mA',
  'psi0-current': 'mA',
  psi3cpu_current: 'mA',
  'psi0soc-current': 'mA',
  psi3gfx_current: 'mA',
  'max-socclk-frequency': 'MHz',
  'min-socclk-frequency': 'MHz',
  'max-fclk-frequency': 'MHz',
  'min-fclk-frequency': 'MHz',
  'max-vcn': 'MHz',
  'min-vcn': 'MHz',
  'max-lclk': 'MHz',
  'min-lclk': 'MHz',
  'max-gfxclk': 'MHz',
  'min-gfxclk': 'MHz',
  'prochot-deassertion-ramp': '',
  'apu-skin-temp': '° C',
  'dgpu-skin-temp': '° C',
  'apu-slow-limit': 'mW',
  'skin-temp-limit': 'mW',
  'gfx-clk': 'MHz',
  'oc-clk': 'MHz'
}
